name: 'Docker Image Testing - Test Package'
description: 'Test a conda package'
inputs:
  conda-activate:
    description: 'An activation script for the conda env to use'
    required: true
  package-path:
    description: 'The path to the .tar.bz2 to test'
    required: true
runs:
  using: composite
  steps:
  - id: 'setup-path'
    shell: bash
    run: echo "${{ github.action_path }}/bin/" >> $GITHUB_PATH

  - name: List repo contents
    run: |
      echo "Repo root:"
      ls -al .
      echo ".github directory:"
      ls -al .github
      echo ".github/actions directory:"
      ls -al .github/actions

  - name: debugme
    shell: bash
    run: |
      ls -R ${{ github.action_path }}

  - id: 'test-package'
    shell: bash
    env:
      PYTHONPATH: "${{ github.action_path }}/../src/"
    run: |
      ${{ inputs.conda-activate }}
      cat <<EOF | test-package.py
      ${{ toJSON(inputs) }}
      EOF
