FROM continuumio/miniconda3:latest

ARG EPOCH
ARG DISTRO

ENV PATH /opt/conda/envs/qiime2-${DISTRO}-${EPOCH}/bin:$PATH
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV MPLBACKEND agg
ENV UNIFRAC_USE_GPU N

RUN conda update -q -y conda
RUN conda install -q -y wget
RUN apt-get install -y procps

COPY ${EPOCH}/${DISTRO}/released/qiime2-${DISTRO}-ubuntu-latest-conda.yml released-env.yml
RUN conda env create -n qiime2-${DISTRO}-${EPOCH} --file released-env.yml \
 && conda clean -a -y \
 && chmod -R a+rwx /opt/conda \
 && rm released-env.yml

RUN /bin/bash -c "source activate qiime2-${DISTRO}-${EPOCH}"
ENV CONDA_PREFIX /opt/conda/envs/qiime2-${DISTRO}-${EPOCH}/
RUN qiime dev refresh-cache
RUN python -c "from qiime2.sdk.parallel_config import get_vendored_config; get_vendored_config()"
RUN echo "source activate qiime2-${DISTRO}-${EPOCH}" >> /root/.bashrc
RUN echo "source tab-qiime" >> /root/.bashrc

VOLUME ["/data"]
WORKDIR /data
