ARG EPOCH
ARG DISTRO

FROM quay.io/rachis/${DISTRO}:${EPOCH}

ARG EPOCH
ARG DISTRO

ENV HOME /home/rachis
ENV XDG_CONFIG_HOME /home/rachis

RUN mkdir /home/rachis
WORKDIR /home/rachis

RUN echo "source activate rachis-${DISTRO}-${EPOCH}" >> $HOME/.bashrc
RUN echo "source tab-qiime" >> $HOME/.bashrc

# Important: let any UID modify these directories so that
# `docker run -u UID:GID` works
RUN chmod -R a+rwx /home/rachis

# update cli prompt to print working directory
RUN echo "export PS1=\"\nCurrent working directory: \\w\n\\$ \"" >> $HOME/.bashrc

# install jupyter lab, configure notebooks for displaying
RUN pip install jupyterlab
RUN jupyter serverextension enable --py qiime2 --sys-prefix

# declare that a volume will be mounted to the working directory
VOLUME "/home/rachis"

# make default jupyter shell be bash
ENV SHELL /bin/bash

# install various useful tools
RUN apt-get update
RUN yes | apt-get install tree vim iputils-ping nano less

# launch jupyter lab on startup
CMD ["jupyter", "lab", \
    "--ip=0.0.0.0", \
    "--port=8888", \
    "--no-browser", \
    "--allow-root", \
    "--NotebookApp.token=''"]
