FROM quay.io/bgruening/galaxy:24.2

ENV \
GALAXY_CONFIG_TOOL_CONFIG_FILE=/qiime2_tools/qiime2_tool_conf.xml \
GALAXY_CONFIG_CONDA_AUTO_INSTALL=true \
GALAXY_CONFIG_CONDA_ENSURE_CHANNELS=https://packages.qiime2.org/qiime2/${EPOCH}/${DISTRO}/released,iuc,conda-forge,bioconda

# Install Visualisation
# This step no longer appears to be working, I am not positive it is mandatory
# RUN install-biojs msa

COPY ${GITHUB_WORKSPACE}/tools/ /qiime2_tools/
# This file does not exist in the galaxy-tools repo
# COPY qiime2_tool_conf.xml /qiime2_tools/

# Mark folders as imported from the host.
VOLUME ["/export/", "/data/", "/var/lib/docker"]

RUN /export/tool_deps/_conda/bin/conda create -y --quiet --solver libmamba --override-channels \
    --channel https://packages.qiime2.org/qiime2/${EPOCH}/${DISTRO}/released --channel iuc --channel \
    conda-forge --channel bioconda --name __qiime2-${DISTRO}@${EPOCH} qiime2-${DISTRO}=${METAPACKAGE}

EXPOSE 80
EXPOSE 21

# Autostart script that is invoked during container start
CMD ["/usr/bin/startup"]
