# Example Dockerfile that can be used for a dev environment image
# More information on how this can be used can be found here:
# https://github.com/lizgehret/readme/DOCKER-DEV-WORKFLOWS.md
FROM condaforge/miniforge3:latest

ARG DISTRO
ARG EPOCH=latest
ARG DISTRO_SUBDIR=passed

ENV PATH /opt/conda/envs/rachis-${DISTRO}-${EPOCH}/bin:$PATH
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV MPLBACKEND agg
ENV UNIFRAC_USE_GPU N
ENV HOME /home/ubuntu
ENV XDG_CONFIG_HOME /home/ubuntu

RUN conda update -q -y conda
RUN conda install -q -y wget
RUN apt-get install -y procps

COPY ${EPOCH}/${DISTRO_SUBDIR}/rachis-${DISTRO}-linux-64-conda.yml dev-env.yml
RUN conda env create -n rachis-${DISTRO}-${EPOCH} --file dev-env.yml \
 && conda clean -a -y \
 && mkdir -p /data /home/ubuntu/.cache \
 && chown -R ubuntu:ubuntu /opt/conda /data /home/ubuntu \
 && rm dev-env.yml

RUN /bin/bash -c "source activate rachis-${DISTRO}-${EPOCH}"
ENV CONDA_PREFIX /opt/conda/envs/rachis-${DISTRO}-${EPOCH}/
USER ubuntu
RUN qiime dev refresh-cache
RUN python -c "from qiime2.sdk.parallel_config import get_vendored_config; get_vendored_config()"
RUN echo "source activate rachis-${DISTRO}-${EPOCH}" >> /home/ubuntu/.bashrc
RUN echo "source tab-qiime" >> /home/ubuntu/.bashrc

# HACK: regression in libc 2.41 causes:
# libssu_nv_avx2.so: cannot enable executable stack as shared object requires: Invalid argument
ENV GLIBC_TUNABLES glibc.rtld.execstack=2

WORKDIR /data
