channels:
- https://packages.qiime2.org/qiime2/2024.5/tiny/passed
- conda-forge
- bioconda
- defaults
dependencies:
- biom-format=2.1.15
- h5py=3.11.0
- hdf5=1.14.3
- mafft=7.525
- matplotlib=3.8.4
- notebook=6.5.5
- numpy=1.26.4
- pandas=2.2.2
- parsl=2024.4.15
- patsy=0.5.6
- pillow=10.3.0
- python=3.10
- python_abi=3.10
- q2-mystery-stew=2024.5.0.dev0
- q2-types=2024.5.0.dev0+5.gd24a69d
- q2cli=2024.5.0.dev0
- qiime2=2024.5.0.dev0+2.g27f5ec0
- r-base=4.2.3
- r-reticulate=1.36.0
- scikit-bio=0.6.0
- scikit-learn=1.4.2
- scipy=1.13.0
- seaborn=0.13.2
- unifrac-binaries=1.4
- unifrac=1.3
extras:
  variant_override:
    qiime2_epoch: '2024.5'
