name: 'Configure conda and friends'
description: 'set up shell env for conda'
runs:
  using: 'composite'
  steps:
    - name: configure conda and friends
      shell: bash
      run: |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate base
        conda config --set always_yes yes
        conda config --set changeps1 no
        conda config --set quiet true
        # TODO: uncomment this whenever conda-forge sorts itself out
        # sudo conda upgrade -n base -q -y -c defaults --override-channels conda
        sudo conda install -n base \
          -q -y \
          -c conda-forge \
          -c defaults \
          --override-channels \
          boa \
          conda-build \
          yq
        conda info -a
        conda config --show
