channels:
- https://packages.qiime2.org/qiime2/2025.10/amplicon/passed
- conda-forge
- bioconda
dependencies:
- biom-format=2.1.16
- blast=2.16.0
- click=8.1.8
- cutadapt=5.1
- deblur=1.1.1
- decorator=5.2.1
- emperor=1.0.4
- fastp=1.0.1
- frictionless=5.5.0
- h5py=3.14.0
- hdf5=1.14.6
- mafft=7.526
- matplotlib=3.10.3
- ncbi-datasets-pyclient=18.4.0
- networkx=3.1
- notebook=7.4.4
- numpy=2.2.6
- pandas=2.3.1
- parsl=2025.7.7
- patsy=1.0.1
- pillow=11.3.0
- python=3.12
- q2-alignment=2025.10.0.dev0
- q2-composition=2025.10.0.dev0
- q2-cutadapt=2025.10.0.dev0
- q2-dada2=2025.10.0.dev0
- q2-deblur=2025.10.0.dev0
- q2-demux=2025.10.0.dev0
- q2-diversity-lib=2025.10.0.dev0
- q2-diversity=2025.10.0.dev0
- q2-emperor=2025.10.0.dev0
- q2-feature-classifier=2025.10.0.dev0
- q2-feature-table=2025.10.0.dev0
- q2-fragment-insertion=2025.10.0.dev0+1.g09bdead
- q2-longitudinal=2025.10.0.dev0
- q2-metadata=2025.10.0.dev0
- q2-mystery-stew=2025.10.0.dev0
- q2-phylogeny=2025.10.0.dev0
- q2-quality-control=2025.10.0.dev0
- q2-quality-filter=2025.10.0.dev0
- q2-sample-classifier=2025.10.0.dev0
- q2-stats=2025.10.0.dev0
- q2-taxa=2025.10.0.dev0
- q2-types=2025.10.0.dev0
- q2-vizard=2025.10.0.dev0
- q2-vsearch=2025.10.0.dev0
- q2cli=2025.10.0.dev0
- q2galaxy=2025.10.0.dev0
- q2templates=2025.10.0.dev0
- qiime2=2025.10.0.dev0
- r-base=4.3.3
- r-optparse=1.7.5
- r-reticulate=1.42.0
- r-vegan=2.7_1
- rescript=2025.10.0.dev0
- rnanorm=2.2.0
- rpy2=3.5.11
- samtools=1.22.1
- scikit-bio=0.7.0
- scikit-learn=1.7.1
- scipy=1.16.0
- seaborn=0.13.2
- sepp=4.5.5
- statsmodels=0.14.5
- tzlocal=5.3
- umap-learn=0.5.9.post2
- unifrac-binaries=1.5
- unifrac=1.5
- vsearch=2.30.0
extras:
  variant_override:
    qiime2_epoch: '2025.10'
