name: 'Test an extracted package from a metapackage'
description: 'test an extracted package from a metapackage'
inputs:
  pkg-url:
    description: 'extracted package conda url'
    required: true
  q2-channel:
    description: 'package channel url'
    required: true
  metapackage-spec:
    description: 'metapackage specification'
    required: true
runs:
  using: 'composite'
  steps:
    - name: run test
      shell: bash
      run: |
        wget ${{ inputs.pkg-url }}
        source "$CONDA/etc/profile.d/conda.sh"
        conda create -n test-env -y -q \
          -c ${{ inputs.q2-channel }} \
          -c conda-forge \
          -c bioconda \
          -c defaults \
          ${{ inputs.metapackage-spec }}
        conda activate test-env
        ${{ github.action_path }}/.github/actions/test-package/bin/run_tests.py *.tar.bz2
