# Take 2
channels:
- https://packages.qiime2.org/qiime2/2023.9/shotgun/passed
- conda-forge
- bioconda
- defaults
dependencies:
- biom-format=2.1.14
- bowtie2=2.5.1
- h5py=3.8.0
- hdf5=1.14.0
- notebook=6.5.5
- numpy=1.24.4
- pandas=1.5.3
- python=3.8
- q2-assembly=2023.9.0
- q2-cutadapt=2023.9.0
- q2-demux=2023.9.0
- q2-diversity-lib=2023.9.0
- q2-diversity=2023.9.0
- q2-emperor=2023.9.0
- q2-feature-classifier=2023.9.0
- q2-feature-table=2023.9.0
- q2-metadata=2023.9.0
- q2-moshpit=2023.9.1
- q2-mystery-stew=2023.9.0
- q2-quality-control=2023.9.0
- q2-quality-filter=2023.9.0
- q2-sample-classifier=2023.9.0
- q2-sapienns=2023.9.0
- q2-taxa=2023.9.0
- q2-types-genomics=2023.9.1
- q2-types=2023.9.0
- q2cli=2023.9.1
- q2templates=2023.9.0
- qiime2=2023.9.1
- r-base=4.2.2
- rescript=2023.9.0
- scikit-bio=0.5.8
- scikit-learn=0.24.1
- scipy=1.10.0
- umap-learn=0.5.4
- unifrac-binaries=1.3.1
- unifrac=1.3
extras:
  variant_override:
    qiime2_epoch: '2023.9'
