channels:
- https://packages.qiime2.org/qiime2/2024.5/shotgun/passed
- conda-forge
- bioconda
- defaults
dependencies:
- biom-format=2.1.14
- bowtie2=2.5.1
- h5py=3.8.0
- hdf5=1.14.0
- matplotlib=3.6.0
- notebook=6.5.5
- numpy=1.24.4
- pandas=1.5.3
- parsl=2023.12.04
- patsy=0.5.3
- python=3.8
- q2-assembly=2024.5.0.dev0
- q2-composition=2024.5.0.dev0
- q2-cutadapt=2024.5.0.dev0
- q2-demux=2024.5.0.dev0
- q2-diversity-lib=2024.5.0.dev0
- q2-diversity=2024.5.0.dev0+1.g99a0cca
- q2-emperor=2024.5.0.dev0
- q2-feature-classifier=2024.5.0.dev0
- q2-feature-table=2024.5.0.dev0+2.g65222bd
- q2-fondue=2024.5.0.dev0
- q2-longitudinal=2024.5.0.dev0
- q2-metadata=2024.5.0.dev0
- q2-moshpit=2024.5.0.dev0+1.gdf1301d
- q2-mystery-stew=2024.5.0.dev0
- q2-quality-control=2024.5.0.dev0
- q2-quality-filter=2024.5.0.dev0
- q2-sample-classifier=2024.5.0.dev0
- q2-sapienns=2024.5.0.dev0
- q2-taxa=2024.5.0.dev0
- q2-types=2024.5.0.dev0+4.g823b5a4
- q2-vsearch=2024.5.0.dev0
- q2cli=2024.5.0.dev0
- q2templates=2024.5.0.dev0
- qiime2=2024.5.0.dev0+1.g6306962
- r-base=4.2.2
- rescript=2024.5.0.dev0+2.ga0df425
- scikit-bio=0.5.8
- scikit-learn=0.24.1
- scipy=1.10.0
- seaborn=0.12.2
- umap-learn=0.5.4
- unifrac-binaries=1.3.2
- unifrac=1.3
extras:
  variant_override:
    qiime2_epoch: '2024.5'
