channels:
- https://packages.qiime2.org/qiime2/2026.4/tiny/staged
- conda-forge
- bioconda
dependencies:
- biom-format=2.1.16
- click=8.1.8
- decorator=4.4.2
- frictionless=5.5.0
- h5py=3.11.0
- hdf5=1.14.3
- networkx=3.1
- notebook=6.5.5
- numpy=2.3.5
- pandas=2.2.2
- parsl=2024.4.15
- python=3.11
- q2-metadata=2026.4.0.dev0
- q2-mystery-stew=2026.4.0.dev0
- q2-types=2026.4.0.dev0+1.gaba63b0
- q2cli=2026.1.0.dev0+10.g537fa80
- q2templates=2026.4.0.dev0+7.g4e67019
- qiime2=2026.4.0.dev0
- r-base=4.3.3
- r-reticulate=1.36.0
- rachis=2026.4.0.dev0+10.ge27e7a9
- rnanorm=2.1.0
- scikit-bio=0.6.2
- scikit-learn=1.6.1
- scipy=1.17.0
- tzlocal=2.1
- unifrac-binaries=1.5.1
- unifrac=1.5.1
extras:
  variant_override:
    qiime2_epoch: '2026.4'
