channels:
- https://packages.qiime2.org/qiime2/2024.5/metagenome/passed
- conda-forge
- bioconda
- defaults
dependencies:
- biom-format=2.1.15
- biopython=1.83
- busco=5.5.0
- bowtie2=2.5.1
- entrezpy=2.1.2
- h5py=3.11.0
- hdf5=1.14.3
- matplotlib=3.8.4
- notebook=6.5.5
- numpy=1.26.4
- pandas=2.2.2
- parsl=2024.4.15
- patsy=0.5.6
- python=3.9.19
- python_abi=3.9
- q2-assembly=2024.5.0.dev0+2.gea8f24f
- q2-composition=2024.5.0.dev0
- q2-cutadapt=2024.5.0.dev0
- q2-demux=2024.5.0.dev0
- q2-diversity-lib=2024.5.0.dev0
- q2-diversity=2024.5.0.dev0+1.g99a0cca
- q2-emperor=2024.5.0.dev0
- q2-feature-classifier=2024.5.0.dev0
- q2-feature-table=2024.5.0.dev0+2.g65222bd
- q2-fondue=2024.5.0.dev0+1.gbc30858
- q2-longitudinal=2024.5.0.dev0
- q2-metadata=2024.5.0.dev0
- q2-moshpit=2024.5.0.dev0+7.gd45c699
- q2-mystery-stew=2024.5.0.dev0
- q2-quality-control=2024.5.0.dev0
- q2-quality-filter=2024.5.0.dev0
- q2-sample-classifier=2024.5.0.dev0
- q2-sapienns=2024.5.0.dev0
- q2-taxa=2024.5.0.dev0
- q2-types=2024.5.0.dev0+5.gd24a69d
- q2-vsearch=2024.5.0.dev0
- q2cli=2024.5.0.dev0
- q2templates=2024.5.0.dev0
- qiime2=2024.5.0.dev0+2.g27f5ec0
- r-base=4.3.3
- r-reticulate=1.36.0
- rescript=2024.5.0.dev0+3.g6e87cfe
- scikit-bio=0.6.0
- scikit-learn=1.4.2
- scipy=1.13.0
- seaborn=0.12.2
- sepp=4.4.0
- tqdm=4.62.3
- umap-learn=0.5.4
- unifrac-binaries=1.4
- unifrac=1.3
extras:
  variant_override:
    qiime2_epoch: '2024.5'
