channels:
- https://packages.qiime2.org/qiime2/2026.10/tiny/passed
- conda-forge
- bioconda
dependencies:
- biom-format=2.1.17
- click=8.1.8
- frictionless=5.5.0
- h5py=3.15.1
- hdf5=1.14.6
- networkx=3.6.1
- numpy=2.4.2
- pandas=2.3.3
- parsl=2026.2.23
- python=3.12
- q2-metadata=2026.10.0.dev0
- q2-mystery-stew=2026.10.0.dev0
- q2-types=2026.10.0.dev0
- q2cli=2026.10.0.dev0
- q2templates=2026.10.0.dev0
- qiime2=2026.10.0.dev0
- r-base=4.5.2
- r-reticulate=1.45.0
- rachis=2026.10.0.dev0+2.g4e70785
- rnanorm=2.1.0
- scikit-bio=0.7.2
- scikit-learn=1.7.1
- scipy=1.17.1
- tzlocal=5.3.1
- unifrac-binaries=1.5.1
- unifrac=1.5.1
extras:
  variant_override:
    qiime2_epoch: '2026.10'
# modified: 2026-08-16
