channels:
- https://packages.qiime2.org/qiime2/2025.7/moshpit/passed
- conda-forge
- bioconda
dependencies:
- biom-format=2.1.16
- biopython=1.83
- bowtie2=2.5.1
- click=8.1.8
- entrezpy=2.1.2
- fastp=0.24.0
- h5py=3.11.0
- hdf5=1.14.3
- mafft=7.526
- matplotlib=3.8.4
- moshpit=2025.7.0.dev0
- notebook=6.5.5
- numpy=1.26.4
- pandas=2.2.2
- parsl=2024.4.15
- patsy=0.5.6
- pysam=0.22.1
- python=3.10
- q2-alignment=2025.7.0.dev0
- q2-annotate=2025.7.0.dev0+1.g7cef034
- q2-assembly=2025.7.0.dev0+1.g3dcd6f6
- q2-composition=2025.7.0.dev0
- q2-cutadapt=2025.7.0.dev0
- q2-demux=2025.7.0.dev0
- q2-diversity-lib=2025.7.0.dev0
- q2-diversity=2025.7.0.dev0
- q2-emperor=2025.7.0.dev0
- q2-feature-classifier=2025.7.0.dev0
- q2-feature-table=2025.7.0.dev0+1.gb601d04
- q2-fondue=2025.7.0.dev0
- q2-longitudinal=2025.7.0.dev0
- q2-metadata=2025.7.0.dev0
- q2-mystery-stew=2025.7.0.dev0
- q2-quality-control=2025.7.0.dev0+2.g0bb5f6a
- q2-quality-filter=2025.7.0.dev0
- q2-sample-classifier=2025.7.0.dev0
- q2-sapienns=2025.7.0.dev0
- q2-sourmash=2025.7.0.dev0
- q2-taxa=2025.7.0.dev0
- q2-types=2025.7.0.dev0+1.g553bf8e
- q2-vizard=2025.7.0.dev0+16.g79ca694
- q2-vsearch=2025.7.0.dev0
- q2cli=2025.7.0.dev0+1.g6fb6bc4
- q2templates=2025.7.0.dev0
- qiime2=2025.7.0.dev0
- r-base=4.3.3
- r-reticulate=1.36.0
- r-vegan=2.6_8
- rescript=2025.7.0.dev0
- rnanorm=2.1.0
- rpy2=3.5.11
- scikit-bio=0.6.2
- scikit-learn=1.4.2
- scipy=1.13.0
- seaborn=0.12.2
- sepp=4.5.5
- spades=4.0.0
- tqdm=4.62.3
- umap-learn=0.5.4
- unifrac-binaries=1.4
- unifrac=1.3
- vsearch=2.22.1
extras:
  variant_override:
    qiime2_epoch: '2025.7'
# modified: 2025-06-10
