channels:
- https://packages.qiime2.org/qiime2/2024.2/amplicon/staged
- conda-forge
- bioconda
- defaults
dependencies:
- biom-format=2.1.14
- h5py=3.8.0
- hdf5=1.14.0
- matplotlib=3.6.0
- notebook=6.5.5
- numpy=1.24.4
- pandas=1.5.3
- parsl=2023.12.04
- patsy=0.5.3
- pillow=9.4.0
- python=3.8
- q2-alignment=2024.2.0
- q2-composition=2024.2.0
- q2-cutadapt=2024.2.0
- q2-dada2=2024.2.0
- q2-deblur=2024.2.0
- q2-demux=2024.2.0
- q2-diversity-lib=2024.2.0
- q2-diversity=2024.2.0
- q2-emperor=2024.2.0
- q2-feature-classifier=2024.2.0
- q2-feature-table=2024.2.2
- q2-fragment-insertion=2024.2.0
- q2-longitudinal=2024.2.0
- q2-metadata=2024.2.0
- q2-mystery-stew=2024.2.0
- q2-phylogeny=2024.2.0
- q2-quality-control=2024.2.0
- q2-quality-filter=2024.2.0
- q2-sample-classifier=2024.2.0
- q2-taxa=2024.2.0
- q2-types=2024.2.0
- q2-vsearch=2024.2.0
- q2cli=2024.2.0
- q2galaxy=2024.2.1
- q2templates=2024.2.0
- qiime2=2024.2.0
- r-base=4.2.2
- rescript=2024.2.2
- scikit-bio=0.5.8
- scikit-learn=0.24.1
- scipy=1.10.0
- seaborn=0.12.2
- unifrac-binaries=1.3.2
- unifrac=1.3
extras:
  variant_override:
    qiime2_epoch: '2023.11'
