channels:
- https://packages.qiime2.org/qiime2/2025.10/tiny/passed
- conda-forge
- bioconda
dependencies:
- biom-format=2.1.16
- click=8.1.8
- decorator=5.2.1
- frictionless=5.5.0
- h5py=3.13.0
- hdf5=1.14.3
- networkx=3.4.2
- notebook=7.4.4
- numpy=2.2.6
- pandas=2.3.1
- parsl=2025.7.28
- python=3.12
- q2-metadata=2025.10.0.dev0
- q2-mystery-stew=2025.10.0.dev0
- q2-types=2025.10.0.dev0+2.g1814a40
- q2cli=2025.10.0.dev0+1.ga9ad621
- q2templates=2025.10.0.dev0
- qiime2=2025.10.0.dev0+4.g6feffe5
- r-base=4.3.3
- r-reticulate=1.43.0
- rnanorm=2.2.0
- scikit-bio=0.7.0
- scikit-learn=1.7.1
- scipy=1.15.2
- tzlocal=5.3
- unifrac-binaries=1.5.1
- unifrac=1.5
extras:
  variant_override:
    qiime2_epoch: '2025.10'
