name: ci-distro-trial-osx-arm

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ci-distro-trial-osx-arm-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  trial:
    uses: ./.github/workflows/ci-distro-trial-platform.yaml
    secrets: inherit
    with:
      platform_label: osx-arm64
      target_subdirs: '["osx-arm64", "noarch"]'
      runner_label: macos-15
      seed_environment_file: seed-environment-conda-osx.yml
      pr_ref: ${{ github.head_ref }}
      conda_subdir_env: osx-arm64
