on:
  workflow_call:
    outputs:
      epoch:
        value: ${{ jobs.prepare.outputs.epoch }}
      distro:
        value: ${{ jobs.prepare.outputs.distro }}
      is-release:
        value: ${{ jobs.prepare.outputs.is-release }}
      is-rebuild:
        value: ${{ jobs.prepare.outputs.is-rebuild }}
      is-language:
        value: ${{ jobs.prepare.outputs.is-language }}
      sibling-ref:
        value: ${{ jobs.prepare.outputs.sibling-ref }}
      matrix-key:
        value: ${{ jobs.prepare.outputs.matrix-key }}
      rev-deps-key:
        value: ${{ jobs.prepare.outputs.rev-deps-key }}
      generation-matrix:
        value: ${{ jobs.prepare.outputs.generation-matrix }}
      patched-channel-key:
        value: ${{ jobs.prepare.outputs.patched-channel-key }}
      rebuilt-channel-key:
        value: ${{ jobs.prepare.outputs.rebuilt-channel-key }}
      seed-environment-key:
        value: ${{ jobs.prepare.outputs.seed-environment-key }}
      solved-environment-key:
        value: ${{ jobs.prepare.outputs.solved-environment-key }}
      repodata-patches-key:
        value: ${{ jobs.prepare.outputs.repodata-patches-key }}

jobs:
  prepare:
    uses: ./.github/workflows/ci-distro-trial_0-prepare-platform.yaml
    secrets: inherit
    with:
      seed_environment_file: seed-environment-conda-osx.yml
      target_subdirs: '["osx-arm64", "noarch"]'
