on:
  workflow_call:
    inputs:
      epoch:
        required: true
        type: string
      distro:
        required: true
        type: string
      is-release:
        required: true
        type: string
      pr-ref:
        required: true
        type: string
      seed-environment-key:
        required: true
        type: string
      solved-environment-key:
        required: true
        type: string
      repodata-patches-key:
        required: true
        type: string
      rebuilt-channel-key:
        required: true
        type: string

jobs:
  upload-builds:
    uses: ./.github/workflows/ci-distro-trial_4-upload-builds-platform.yaml
    secrets: inherit
    with:
      epoch: ${{ inputs.epoch }}
      distro: ${{ inputs.distro }}
      is-release: ${{ inputs.is-release }}
      pr-ref: ${{ inputs.pr-ref }}
      seed-environment-key: ${{ inputs.seed-environment-key }}
      solved-environment-key: ${{ inputs.solved-environment-key }}
      repodata-patches-key: ${{ inputs.repodata-patches-key }}
      rebuilt-channel-key: ${{ inputs.rebuilt-channel-key }}
      seed_environment_file: seed-environment-conda-osx.yml
