on:
  workflow_call:
    inputs:
      seed-environment-key:
        required: true
        type: string
      solved-environment-key:
        required: true
        type: string
      rebuilt-channel-key:
        required: true
        type: string
      patched-channel-key:
        required: true
        type: string
      distro-name:
        required: true
        type: string
    outputs:
      distro-version:
        value: ${{ jobs.setup-version.outputs.version }}
      channels:
        value: ${{ jobs.build-metapackage.outputs.channels }}

env:
  patched_channel_path: './patched-channel'
  rebuilt_channel_path: './rebuilt-channel'
  seed_environment_path: './seed-env'
  environment_prefix: './test-env/'

jobs:
  setup-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create-version.outputs.version }}
    steps:
      - id: create-version
        shell: bash
        run: |
          echo version=$(
            python -c "import datetime; print(datetime.datetime.utcnow().strftime('%Y.%m.%d.%H.%M.%S'))"
          ) >> $GITHUB_OUTPUT

  build-metapackage:
    needs: [setup-version]
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: condaforge/linux-anvil-x86_64:alma8
    outputs:
      channels: ${{ steps.build-meta.outputs.channels }}
    steps:

      - name: fetch seed env
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.seed-environment-key }}
          path: ${{ env.seed_environment_path }}

      - uses: actions/download-artifact@v4
        name: 'Fetch base channel with patches'
        with:
          name: ${{ inputs.patched-channel-key }}
          path: ${{ env.patched_channel_path }}

      - name: fetch rebuilt channel
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.rebuilt-channel-key }}
          path: ${{ env.rebuilt_channel_path }}

      - uses: qiime2/action-library-packaging/environment-linux@beta
        id: build-env
        name: "Set up build env"

      - uses: qiime2/action-library-packaging/build-metapackage-linux@beta
        name: "Build metapackage"
        id: build-meta
        with:
          conda-activate: ${{ steps.build-env.outputs.conda-activate }}
          channels: '["${{ env.rebuilt_channel_path }}", "${{ env.patched_channel_path }}"]'
          metapackage-name: ${{ inputs.distro-name }}
          metapackage-version: ${{ needs.setup-version.outputs.version }}
          seed-environment: '${{ env.seed_environment_path }}/seed-environment-conda-linux.yml'
          output-channel: ${{ env.rebuilt_channel_path }}
