name: ci-distro-trial-osx

on:
  pull_request:
    branches: [dev]
    paths:
      - 20*.*/*/passed/seed-environment-conda-osx.yml
      - 20*.*/*/released/seed-environment-conda-osx.yml

concurrency:
  group: ci-distro-trial-osx-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  osx-intel:
    if: ${{ startsWith(github.head_ref, 'Prepare-osx-64-') }}
    uses: ./.github/workflows/ci-distro-trial-osx-intel.yaml
    secrets: inherit

  osx-arm:
    if: ${{ startsWith(github.head_ref, 'Prepare-osx-arm64-') }}
    uses: ./.github/workflows/ci-distro-trial-osx-arm.yaml
    secrets: inherit
