on:
  workflow_call:
    inputs:
      seed-environment-key:
        required: true
        type: string
      solved-environment-key:
        required: true
        type: string
      rebuilt-channel-key:
        required: true
        type: string
      patched-channel-key:
        required: true
        type: string
      distro-name:
        required: true
        type: string
    outputs:
      distro-version:
        value: ${{ jobs.build-metapackage.outputs.distro-version }}

jobs:
  build-metapackage:
    uses: ./.github/workflows/ci-distro-trial_2-build-metapackage-platform.yaml
    with:
      seed-environment-key: ${{ inputs.seed-environment-key }}
      solved-environment-key: ${{ inputs.solved-environment-key }}
      rebuilt-channel-key: ${{ inputs.rebuilt-channel-key }}
      patched-channel-key: ${{ inputs.patched-channel-key }}
      distro-name: ${{ inputs.distro-name }}
      runner_label: ubuntu-latest
      platform_label: linux-64
      seed_environment_file: seed-environment-conda-linux.yml
