on:
  workflow_call:
    inputs:
      rev-deps-key:
        required: true
        type: string
      patched-channel-key:
        required: true
        type: string
      rebuilt-channel-key:
        required: true
        type: string
      seed-environment-key:
        required: true
        type: string
      matrix-key:
        required: true
        type: string
      matrix-index:
        required: true
        type: number
      platform_label:
        required: true
        type: string
      target_subdirs:
        required: true
        type: string
      sibling-ref:
        required: true
        type: string
      is-rebuild:
        required: true
        type: string
      is-language:
        required: true
        type: string

jobs:
  build-generation:
    uses: ./.github/workflows/ci-distro-trial_1-build-generation-platform.yaml
    secrets: inherit
    with:
      rev-deps-key: ${{ inputs.rev-deps-key }}
      patched-channel-key: ${{ inputs.patched-channel-key }}
      rebuilt-channel-key: ${{ inputs.rebuilt-channel-key }}
      seed-environment-key: ${{ inputs.seed-environment-key }}
      matrix-key: ${{ inputs.matrix-key }}
      matrix-index: ${{ inputs.matrix-index }}
      platform_label: ${{ inputs.platform_label }}
      target_subdirs: ${{ inputs.target_subdirs }}
      sibling-ref: ${{ inputs.sibling-ref }}
      is-rebuild: ${{ inputs.is-rebuild }}
      is-language: ${{ inputs.is-language }}
      runner_label: macos-15-intel
      seed_environment_file: seed-environment-conda-osx.yml
