name: cron-prepare-osx-arm
on:
  workflow_dispatch: {}

jobs:
  tiny:
    uses: ./.github/workflows/create-prepare-pr-osx-arm.yaml
    secrets: inherit
    with:
      distro: tiny

  amplicon:
    needs: [tiny]
    uses: ./.github/workflows/create-prepare-pr-osx-arm.yaml
    secrets: inherit
    with:
      distro: amplicon
