name: cron-prepare-osx-intel
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * SUN

jobs:
  tiny:
    uses: ./.github/workflows/create-prepare-pr-osx-intel.yaml
    secrets: inherit
    with:
      distro: tiny

  amplicon:
    needs: [tiny]
    uses: ./.github/workflows/create-prepare-pr-osx-intel.yaml
    secrets: inherit
    with:
      distro: amplicon
