name: cron-prepare-linux
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * SUN

jobs:
  tiny:
    uses: ./.github/workflows/create-prepare-pr-linux.yaml
    secrets: inherit
    with:
      distro: tiny

  qiime2:
    needs: [tiny]
    uses: ./.github/workflows/create-prepare-pr-linux.yaml
    secrets: inherit
    with:
      distro: qiime2

  moshpit:
    needs: [tiny, qiime2]
    uses: ./.github/workflows/create-prepare-pr-linux.yaml
    secrets: inherit
    with:
      distro: moshpit

  pathogenome:
    needs: [tiny, qiime2, moshpit]
    uses: ./.github/workflows/create-prepare-pr-linux.yaml
    secrets: inherit
    with:
      distro: pathogenome

  docker-moshpit:
    needs: [moshpit]
    uses: ./.github/workflows/dev-docker.yaml
    secrets: inherit
    with:
      distro: moshpit
