# # Example of workflow trigger for calling workflow (the client).
# name: ci-dev
# on:
#   pull_request:
#     branches: ["dev"]
#   push:
#     branches: ["dev"]
# jobs:
#   ci:
#     uses: qiime2/distributions/.github/workflows/lib-ci-dev.yaml@dev
#     with:
#       distro: core

on:
  workflow_call:
    inputs:
      distro:
        description: "Distro to test with"
        type: string
        required: true

      epoch:
        type: string
        required: true

      recipe-path:
        description: "Path to recipe"
        type: string
        required: false
        default: 'conda-recipe/'

      additional-reports-path:
        description: "Path of additional reports to store in GH artifact"
        type: string
        required: false
        default: ''

      additional-reports-name:
        description: "Name of GH artifact for additional reports"
        type: string
        required: false
        default: 'reports'

    outputs:
      additional-reports-path:
        value: ${{ inputs.additional-reports-path }}
      additional-reports-name:
        value: ${{ inputs.additional-reports-name }}

jobs:
  build-and-test:
    name: '${{ github.event.repository.name }} (macos-15-intel)'
    needs: setup
    strategy:
      fail-fast: false
    runs-on: macos-15-intel
    env:
      plugin_path: ./repo
      built_channel_path: ./built-channel
      seed_env_path: ${{ inputs.epoch }}/${{ inputs.distro }}/staged/seed-environment-conda-osx.yml
      env_prefix: ./test-env
    steps:
      - uses: actions/checkout@v4
        id: checkout-repo
        with:
          path: ${{ env.plugin_path }}
          fetch-depth: 0
          submodules: true

      - uses: actions/checkout@v3
        with:
          repository: qiime2/distributions
          path: ./distro
          sparse-checkout: ${{ env.seed_env_path }}

      - uses: qiime2/action-library-packaging/environment@beta
        name: 'Set up build environment'
        id: setup-conda

      - name: 'Set up test environment'
        run: |
          conda create -y -p ${{ env.env_prefix }}
          mkdir -p ${{ env.env_prefix }}/etc
          cat <<EOF > '${{ env.env_prefix }}/etc/activate.sh'
            . "$CONDA/etc/profile.d/conda.sh"
            conda activate '${{ env.env_prefix }}'
          EOF
          chmod +x '${{ env.env_prefix }}/etc/activate.sh'

      - name: 'Set up built channel'
        run: |
          ${{ steps.setup-conda.outputs.conda-activate }}
          mkdir -p ${{ env.built_channel_path }}
          python -m conda_index ${{ env.built_channel_path }}

      - uses: qiime2/action-library-packaging/make-conda-config@beta
        name: 'Create conda build config'
        id: make-cbc
        with:
          conda-activate: ${{ steps.setup-conda.outputs.conda-activate }}
          seed-environment: ./distro/${{ env.seed_env_path }}
          conda-build-config: 'conda_build_config.yml'
          channels: '["${{ env.built_channel_path }}"]'

      - uses: qiime2/action-library-packaging/build-package@beta
        name: 'Build ${{ github.event.repository.name }}'
        id: build-package
        with:
          conda-activate: ${{ steps.setup-conda.outputs.conda-activate }}
          recipe-path: ${{ env.plugin_path }}/${{ inputs.recipe-path }}
          conda-build-config: ${{ steps.make-cbc.outputs.conda-build-config }}
          channels: ${{ steps.make-cbc.outputs.channels }}
          output-channel: ${{ env.built_channel_path }}

      - uses: qiime2/action-library-packaging/install-package@beta
        name: 'Install ${{ github.event.repository.name }}'
        with:
          conda-activate: ${{ steps.setup-conda.outputs.conda-activate }}
          package-name: ${{ steps.build-package.outputs.package-name }}
          package-version: ${{ steps.build-package.outputs.package-version }}
          conda-prefix: ${{ env.env_prefix }}
          channels: ${{ steps.make-cbc.outputs.channels }}

      - name: 'set up yaml for test env'
        shell: bash
        run: |
          source ${{ env.env_prefix }}/etc/activate.sh
          conda activate '${{ env.env_prefix }}'
          pip install pyyaml

      - uses: qiime2/action-library-packaging/test-package@beta
        name: 'Test ${{ github.event.repository.name }}'
        with:
          conda-activate: source ${{ env.env_prefix }}/etc/activate.sh
          package-path: ${{ env.built_channel_path }}/${{ steps.build-package.outputs.conda-subdir }}/${{ steps.build-package.outputs.package-filename }}
          channels: ${{ steps.make-cbc.outputs.channels }}
