# triggered on GH release
name: community-release-env
on:
  release:
    types: [published]
  # PR gets opened with the following changes

jobs:
  create-pr:
    runs-on: ubuntu-latest
  steps:

    - uses: actions/checkout@v3

    - name: Get release info
      id: get_release_name
      run: |
        RELEASE_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest")
        LATEST_RELEASE_NAME=$(echo "$RELEASE_JSON" | jq -r '.name')
        echo "Latest release name: $LATEST_RELEASE_NAME"
        echo "::set-output name=release_name::$LATEST_RELEASE_NAME"

    # - name: Open PR with updated release env
    #   id:
    #   needs: ${{ steps.get_release_name.outputs.release_name }}

  # comment added to PR with instructions
    # if pass: go ahead and merge me!
    # if fail: examine environment conflicts, etc

# release env file gets updated
  # name changed to match the release version
  # branch changed in install to match release version

# ci runs to assert a working env (separate job?)
  # test out install with same instructions as community members have
