name: test-docker-image
on:
  workflow_dispatch:
    inputs:
      epoch:
        required: true
        type: string
      distro:
        required: true
        type: string

jobs:
  prepare_matrix:
    name: Create package matrix to test
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.construct-matrix.outputs.matrix }}
    steps:
      - name: setup miniforge
        # Replaces conda-incubator/setup-miniconda@v3
        uses: qiime2-cutlery/setup-miniconda@v3
        with:
          activate-environment: ''
          architecture: 'x64'
          auto-activate-base: true
          miniforge-version: 'latest'

      - name: construct and store retest matrix
        id: construct-matrix
        run: |
          mkdir retest-matrix/

          conda search --channel https://packages.qiime2.org/qiime2/${{ inputs.epoch }}/${{ inputs.distro }}/released/ --override-channels --json > retest-matrix/packages.json

          python - <<EOF
          import json
          import os

          distro = "${{ inputs.distro }}"
          metapackage_name = f"qiime2-{distro}"

          with open('retest-matrix/packages.json', 'r') as fh:
            packages = json.load(fh)
            retest_matrix = set(packages.keys())

          retest_matrix.discard(metapackage_name)
          json_matrix = json.dumps(sorted(retest_matrix))

          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            fh.write(f'matrix={json_matrix}\n')

          EOF

  install_and_test:
    name: install and test
    needs: prepare_matrix
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.prepare_matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    container: quay.io/qiime2/${{ inputs.distro }}:${{ inputs.epoch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install jq
        run: |
          apt-get update && apt-get install -y jq && rm -rf /var/lib/apt/lists/*

      - name: create conda activation script
        run: |
          echo "source /opt/conda/etc/profile.d/conda.sh && conda activate base" > activate.sh
          chmod +x activate.sh

      - name: download ${{ matrix.package }}
        id: download
        run: |
          PACKAGE=${{ matrix.package }}
          CHANNEL_URL="https://packages.qiime2.org/qiime2/${{ inputs.epoch }}/${{ inputs.distro }}/released/linux-64"

          curl -sSL "${CHANNEL_URL}/repodata.json" > repodata.json

          PACKAGE_FILE=$(jq -r --arg name "$PACKAGE" '
            .packages | to_entries
            | map(select(.value.name == $name))
            | sort_by(.value.timestamp)
            | reverse | .[0].key' repodata.json)

          echo "PACKAGE_FILE=$PACKAGE_FILE" >> $GITHUB_ENV

          curl -O "${CHANNEL_URL}/${PACKAGE_FILE}"

      - name: Write test runner script
        run: |
          mkdir -p test-bin
          cat <<EOF > test-bin/test-package.py
          #!/usr/bin/env python

          import importlib
          import itertools
          import subprocess
          import tarfile
          import yaml
          import json
          import os
          import sys

          from alp.common import ActionAdapter

          def find_tests(package_path):
              with tarfile.open(package_path, mode='r:bz2') as fh:
                  recipe_fh = fh.extractfile('info/recipe/meta.yaml')
                  tests = yaml.safe_load(recipe_fh).get('test')
              return tests

          def install_requires(reqs, channels):
              print(f'Installing: {" ".join(reqs)}', flush=True)
              channels = itertools.chain.from_iterable(
                  [('-c', channel) for channel in channels])
              subprocess.run(['conda', 'install',
                              *channels,
                              '-y', '-q',
                              *reqs],
                             check=True)

          def run_imports(imports):
              for imp in imports:
                  print(f'Importing: {imp}', flush=True)
                  importlib.import_module(imp)

          def run_commands(commands):
              for cmd in commands:
                print(f'Running: {cmd}', flush=True)
                subprocess.run(cmd, shell=True, check=True)

          def main(package_path, channels, conda_activate):
              tests = find_tests(package_path)
              print(tests, flush=True)
              if 'requires' in tests:
                  install_requires(tests['requires'], channels)
              if 'imports' in tests:
                  run_imports(tests['imports'])
              if 'commands' in tests:
                  run_commands(tests['commands'])

          if __name__ == '__main__':
              ActionAdapter(main)
          EOF

          chmod +x test-bin/test-package.py

      - name: run tests for ${{ matrix.package }}
        shell: bash
        env:
          PYTHONPATH: ${{ github.workspace }}/.github/actions/src
        run: |
          ./activate.sh

          echo '{
            "conda-activate": "./activate.sh",
            "package-path": "./${{ env.PACKAGE_FILE }}",
            "channels": ["https://packages.qiime2.org/qiime2/${{ inputs.epoch }}/${{ inputs.distro }}/released", "conda-forge", "bioconda"]
          }' | ./test-bin/test-package.py
